-- Auto-generated by AutoFabric alembic adapter
-- job_key: job_006
-- job_name: 设计数据库模型与迁移方案
-- build_target_hint: migration_plan

BEGIN;

-- TODO: replace placeholder DDL with real migration steps.
ALTER TABLE projects
    ADD COLUMN IF NOT EXISTS autofabric_note TEXT;

COMMIT;
