-- Auto-generated by AutoFabric backend_project_codegen
-- project_id: 53
-- selected_tool: alembic_adapter
-- adapter_mode: alembic_migration

CREATE TABLE IF NOT EXISTS autofabric_order (
    id BIGSERIAL PRIMARY KEY,
    project_id BIGINT NOT NULL,
    order_no TEXT NOT NULL,
    status TEXT NOT NULL,
    customer_name TEXT NOT NULL,
    amount TEXT NOT NULL,
    created_at TEXT NOT NULL,
    runtime_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
