-- Auto-generated by AutoFabric backend_project_codegen
-- project_id: 72
-- selected_tool: alembic_adapter
-- adapter_mode: alembic_migration

CREATE TABLE IF NOT EXISTS autofabric_task (
    id BIGSERIAL PRIMARY KEY,
    project_id BIGINT NOT NULL,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    status TEXT NOT NULL,
    priority TEXT NOT NULL,
    assignee TEXT NOT NULL,
    created_at TEXT NOT NULL,
    runtime_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
