-- Auto-generated by AutoFabric backend_project_codegen
-- project_id: 46
-- selected_tool: alembic_adapter
-- adapter_mode: alembic_migration

CREATE TABLE IF NOT EXISTS autofabric_toolhistory (
    id BIGSERIAL PRIMARY KEY,
    project_id BIGINT NOT NULL,
    input_value TEXT NOT NULL,
    output_value TEXT NOT NULL,
    created_at TEXT NOT NULL,
    runtime_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
