from fastapi import APIRouter
from pydantic import BaseModel
import psycopg.types.json

from app.db.pool import get_conn
from app.errors import not_found
from app.services.stage_executor import advance_stage
from app.stages.delivery import generate_docs, generate_deploy_config, assemble_delivery

router = APIRouter(prefix="/deliveries", tags=["deliveries"])


class DeliveryCreate(BaseModel):
    project_id: int
    summary_md: str | None = None


@router.post("")
def create_delivery(payload: DeliveryCreate):
    with get_conn() as conn:
        cur = conn.cursor()
        cur.execute("SELECT id FROM projects WHERE id = %s", (payload.project_id,))
        if not cur.fetchone():
            not_found("project", payload.project_id)

        project_id = payload.project_id

        # Gather context for LLM doc generation
        cur.execute(
            "SELECT title, summary, target_users, problem_statement FROM requirement_cards WHERE project_id = %s ORDER BY id DESC LIMIT 1",
            (project_id,),
        )
        req = cur.fetchone()
        req_card = {"title": req[0] or "", "summary": req[1] or "", "target_users": req[2] or "", "problem_statement": req[3] or ""} if req else {}

        cur.execute("SELECT api_draft_json, module_map_json FROM prototype_specs WHERE project_id = %s ORDER BY id DESC LIMIT 1", (project_id,))
        proto = cur.fetchone()
        api_design = proto[0] if proto and proto[0] else None
        architecture = proto[1] if proto and proto[1] else None

        tech_stack = req_card.get("tech_stack_suggestion") if isinstance(req_card.get("tech_stack_suggestion"), dict) else None

        # Generate docs and deploy config with LLM
        docs = generate_docs(req_card, api_design=api_design, architecture=architecture)
        deploy = generate_deploy_config(req_card, tech_stack=tech_stack)

        # Assemble delivery package on disk
        delivery_dir = assemble_delivery(project_id, docs, deploy)

        summary_md = payload.summary_md or docs.get("readme", "# Delivery Package\n\nGenerated by AutoFabric.")

        cur.execute(
            """
            INSERT INTO delivery_packages (
                project_id, summary_md, prototype_refs_json, engineering_refs_json,
                testing_refs_json, process_refs_json, next_step_json, published_at, status
            )
            VALUES (%s, %s, %s::jsonb, %s::jsonb, %s::jsonb, %s::jsonb, %s::jsonb, NOW(), 'published')
            RETURNING id, project_id, summary_md, prototype_refs_json, engineering_refs_json, testing_refs_json, process_refs_json, next_step_json, published_at, status, created_at, updated_at
            """,
            (
                project_id, summary_md,
                psycopg.types.json.Json(["prototype_specs"]),
                psycopg.types.json.Json(["orchestration_plans", "agent_jobs"]),
                psycopg.types.json.Json(["testing_runs"]),
                psycopg.types.json.Json(["stage_transitions", "human_approvals"]),
                psycopg.types.json.Json({"delivery_dir": delivery_dir}),
            ),
        )
        created = cur.fetchone()

        advance_stage(project_id, "testing", "delivery", "delivery_created", conn=conn)
        conn.commit()
        cur.close()

    result = _row_to_delivery(created)
    result["delivery_dir"] = delivery_dir
    return result


@router.get("/by-project/{project_id}")
def list_deliveries_by_project(project_id: int):
    with get_conn() as conn:
        cur = conn.cursor()
        cur.execute(
            """
            SELECT id, project_id, summary_md, prototype_refs_json, engineering_refs_json, testing_refs_json, process_refs_json, next_step_json, published_at, status, created_at, updated_at
            FROM delivery_packages
            WHERE project_id = %s
            ORDER BY id DESC
            """,
            (project_id,),
        )
        rows = cur.fetchall()
        cur.close()

    return {
        "items": [_row_to_delivery(r) for r in rows],
        "count": len(rows),
    }


@router.get("/{delivery_id}")
def get_delivery(delivery_id: int):
    with get_conn() as conn:
        cur = conn.cursor()
        cur.execute(
            """
            SELECT id, project_id, summary_md, prototype_refs_json, engineering_refs_json, testing_refs_json, process_refs_json, next_step_json, published_at, status, created_at, updated_at
            FROM delivery_packages
            WHERE id = %s
            """,
            (delivery_id,),
        )
        row = cur.fetchone()
        cur.close()

    if not row:
        not_found("delivery", delivery_id)

    return _row_to_delivery(row)


def _row_to_delivery(r):
    return {
        "id": r[0], "project_id": r[1], "summary_md": r[2],
        "prototype_refs_json": r[3], "engineering_refs_json": r[4],
        "testing_refs_json": r[5], "process_refs_json": r[6],
        "next_step_json": r[7],
        "published_at": r[8].isoformat() if r[8] else None,
        "status": r[9],
        "created_at": r[10].isoformat() if r[10] else None,
        "updated_at": r[11].isoformat() if r[11] else None,
    }
