"""init schema

Revision ID: 531496a2ad76
Revises: 
Create Date: 2026-03-20 09:16:42.814539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '531496a2ad76'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verifications')
    op.drop_table('executions')
    op.drop_table('artifacts')
    op.alter_column('goals', 'goal_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True,
               existing_server_default=sa.text("'environment_build'::character varying"))
    op.alter_column('goals', 'risk_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'low'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goals', 'risk_level',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'low'::character varying"))
    op.alter_column('goals', 'goal_type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'environment_build'::character varying"))
    op.create_table('artifacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('outcome_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artifact_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], name=op.f('artifacts_outcome_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('artifacts_pkey'))
    )
    op.create_table('executions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('outcome_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('executor_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'queued'::character varying"), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], name=op.f('executions_outcome_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('executions_pkey'))
    )
    op.create_table('verifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('outcome_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('check_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('result', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], name=op.f('verifications_outcome_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('verifications_pkey'))
    )
    # ### end Alembic commands ###
