#!/usr/bin/env python3
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, List


ROOT_DIR = Path(__file__).resolve().parents[2]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from backend.app.core.database import SessionLocal  # noqa: E402
from backend.app.services.project_codegen_service import GENERATED_DIR  # noqa: E402
from backend.app.services.project_codegen_service import _latest_prototype_spec  # noqa: E402
from backend.app.services.project_codegen_service import _latest_requirement  # noqa: E402
from backend.app.services.project_codegen_service import _latest_requirement_spec  # noqa: E402
from backend.app.services.project_codegen_service import _safe_slug  # noqa: E402
from backend.app.services.project_codegen_service import _template_theme  # noqa: E402


def _safe_python_class_name(name: str, fallback: str = "GeneratedRecord") -> str:
    parts = re.findall(r"[A-Za-z0-9]+", str(name or ""))
    if not parts:
        return fallback
    return "".join(part[:1].upper() + part[1:] for part in parts)


def _safe_python_field(name: str, fallback: str = "title") -> str:
    value = re.sub(r"[^A-Za-z0-9_]+", "_", str(name or "")).strip("_").lower()
    if not value:
        value = fallback
    if value[0].isdigit():
        value = f"field_{value}"
    if value in {"class", "from", "import", "pass", "return", "global", "lambda"}:
        value = f"field_{value}"
    return value


def _safe_field_list(fields: List[Any]) -> List[str]:
    normalized: List[str] = []
    seen = set()
    for item in fields or []:
        field_name = _safe_python_field(str(item or ""))
        if field_name and field_name not in seen and field_name != "id":
            normalized.append(field_name)
            seen.add(field_name)
    return normalized or ["title", "status", "created_at"]


def _safe_table_name(raw_name: str, router_name: str, project_id: int) -> str:
    ascii_name = re.sub(r"[^a-z0-9_]+", "_", str(raw_name or "").lower()).strip("_")
    ascii_name = ascii_name or f"project_{project_id}_{router_name}"
    return f"autofabric_{ascii_name}"


def _prepend_metadata_comment(content: str, metadata: Dict[str, Any]) -> str:
    header = [
        "Auto-generated by AutoFabric backend_project_codegen",
        f"project_id: {metadata.get('project_id')}",
        f"selected_tool: {metadata.get('selected_tool') or ''}",
        f"adapter_mode: {metadata.get('adapter_mode') or ''}",
        f"adapter_intent: {metadata.get('adapter_intent') or ''}",
    ]
    return '"""\n' + "\n".join(header) + '\n"""\n\n' + content


def _build_runtime_schema_content(entity_name: str, fields: List[str]) -> str:
    create_lines = "\n".join([f"    {field}: str" for field in fields])
    read_lines = "\n".join(["    id: int"] + [f"    {field}: str" for field in fields])
    return f"""from pydantic import BaseModel


class {entity_name}Create(BaseModel):
{create_lines}


class {entity_name}Read(BaseModel):
{read_lines}
"""


def _build_runtime_model_content(entity_name: str, table_name: str, fields: List[str]) -> str:
    column_lines = "\n".join([f'    {field} = Column(String(255), nullable=False)' for field in fields])
    return f"""from sqlalchemy import Column, Integer, String
from backend.app.core.database import Base


class {entity_name}(Base):
    __tablename__ = "{table_name}"

    id = Column(Integer, primary_key=True, index=True)
    project_id = Column(Integer, nullable=False, index=True)
{column_lines}
"""


def _build_runtime_service_content(
    *,
    entity_name: str,
    table_name: str,
    fields: List[str],
    project_id: int,
    template_name: str,
) -> str:
    insert_columns = ", ".join(["project_id", *fields])
    insert_values = ", ".join([":project_id", *[f":{field}" for field in fields]])
    create_columns = ",\n".join([f"            {field} TEXT NOT NULL" for field in fields])
    return f"""from typing import Any, Dict, List

from sqlalchemy import text
from sqlalchemy.orm import Session


TABLE_NAME = "{table_name}"
PROJECT_ID = {project_id}
TEMPLATE_NAME = "{template_name}"
FIELD_NAMES = {fields!r}


def ensure_{entity_name.lower()}_table(db: Session) -> None:
    db.execute(text(\"\"\"
        CREATE TABLE IF NOT EXISTS {table_name} (
            id BIGSERIAL PRIMARY KEY,
            project_id BIGINT NOT NULL,
{create_columns},
            runtime_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    \"\"\"))
    db.commit()


def list_{entity_name.lower()}_items(db: Session) -> List[Dict[str, Any]]:
    ensure_{entity_name.lower()}_table(db)
    rows = db.execute(
        text(\"\"\"
            SELECT id, {", ".join(fields)}
            FROM {table_name}
            WHERE project_id = :project_id
            ORDER BY id DESC
            LIMIT 200
        \"\"\"),
        {{"project_id": PROJECT_ID}},
    ).mappings().all()
    return [dict(row) for row in rows]


def create_{entity_name.lower()}_item(db: Session, payload: Dict[str, Any]) -> Dict[str, Any]:
    ensure_{entity_name.lower()}_table(db)
    row = db.execute(
        text(\"\"\"
            INSERT INTO {table_name} ({insert_columns})
            VALUES ({insert_values})
            RETURNING id, {", ".join(fields)}
        \"\"\"),
        {{"project_id": PROJECT_ID, **payload}},
    ).mappings().first()
    db.commit()
    item = dict(row) if row else {{}}
    item["template"] = TEMPLATE_NAME
    return item
"""


def _build_runtime_router_content(
    *,
    entity_name: str,
    table_name: str,
    router_name: str,
    fields: List[str],
    project_id: int,
    title: str,
    template_name: str,
    metadata: Dict[str, Any],
) -> str:
    schema_lines = "\n".join([f"    {field}: str" for field in fields])
    payload_map = ",\n            ".join([f'"{field}": payload.{field}' for field in fields])
    create_columns_sql = ",\n".join([f"            {field} TEXT NOT NULL" for field in fields])
    select_columns = ", ".join(fields)
    prefix = f"/generated/project-{project_id}/{router_name}"
    return f'''"""
Auto-generated by AutoFabric backend_project_codegen
project_id: {project_id}
router_name: {router_name}
selected_tool: {metadata.get("selected_tool") or ""}
adapter_mode: {metadata.get("adapter_mode") or ""}
"""

from fastapi import APIRouter, Depends
from pydantic import BaseModel
from sqlalchemy import text
from sqlalchemy.orm import Session

from backend.app.core.database import get_db


PROJECT_ID = {project_id}
TABLE_NAME = "{table_name}"
TEMPLATE_NAME = "{template_name}"

router = APIRouter(prefix="{prefix}", tags=["{title}"])


class {entity_name}Create(BaseModel):
{schema_lines}


def _ensure_table(db: Session) -> None:
    db.execute(text("""
        CREATE TABLE IF NOT EXISTS {table_name} (
            id BIGSERIAL PRIMARY KEY,
            project_id BIGINT NOT NULL,
{create_columns_sql},
            runtime_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
    """))
    db.commit()


@router.get("/")
def list_items(db: Session = Depends(get_db)):
    _ensure_table(db)
    rows = db.execute(
        text("""
            SELECT id, {select_columns}
            FROM {table_name}
            WHERE project_id = :project_id
            ORDER BY id DESC
            LIMIT 200
        """),
        {{"project_id": PROJECT_ID}},
    ).mappings().all()
    return {{
        "template": TEMPLATE_NAME,
        "table_name": TABLE_NAME,
        "project_id": PROJECT_ID,
        "items": [dict(row) for row in rows],
    }}


@router.post("/")
def create_item(payload: {entity_name}Create, db: Session = Depends(get_db)):
    _ensure_table(db)
    row = db.execute(
        text("""
            INSERT INTO {table_name} (project_id, {select_columns})
            VALUES (:project_id, {", ".join([f":{field}" for field in fields])})
            RETURNING id, {select_columns}
        """),
        {{
            "project_id": PROJECT_ID,
            {payload_map}
        }},
    ).mappings().first()
    db.commit()
    item = dict(row) if row else {{}}
    item["template"] = TEMPLATE_NAME
    return item
'''


def _build_runtime_migration_content(table_name: str, fields: List[str], project_id: int, metadata: Dict[str, Any]) -> str:
    field_lines = ",\n".join([f"    {field} TEXT NOT NULL" for field in fields])
    return f"""-- Auto-generated by AutoFabric backend_project_codegen
-- project_id: {project_id}
-- selected_tool: {metadata.get("selected_tool") or ""}
-- adapter_mode: {metadata.get("adapter_mode") or ""}

CREATE TABLE IF NOT EXISTS {table_name} (
    id BIGSERIAL PRIMARY KEY,
    project_id BIGINT NOT NULL,
{field_lines},
    runtime_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
"""


def _write(path: Path, content: str) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return str(path)


def _cleanup_matching_files(root: Path, pattern: str) -> None:
    if not root.exists():
        return
    for item in root.glob(pattern):
        if item.is_file():
            item.unlink()


def _load_context(project_id: int) -> Dict[str, Any]:
    with SessionLocal() as db:
        requirement = _latest_requirement(db, project_id)
        if not requirement:
            raise ValueError("latest requirement not found")
        requirement_spec = _latest_requirement_spec(db, project_id) or {}
        prototype_spec = _latest_prototype_spec(db, project_id) or {}

    title = str(requirement.get("title") or f"Project {project_id}")
    goal = str(requirement.get("normalized_goal") or requirement.get("raw_input") or title)
    template_key = str(requirement_spec.get("template_key") or "")
    template_name = str(requirement_spec.get("template_name") or "")
    theme = _template_theme(template_key)

    entities = requirement_spec.get("data_entities_json") or [{"name": "MainRecord", "fields": ["title", "status", "created_at"]}]
    main_entity = entities[0] if entities else {"name": "MainRecord", "fields": ["title", "status", "created_at"]}
    raw_entity_name = str(main_entity.get("name") or "MainRecord")
    entity_name = _safe_python_class_name(raw_entity_name)
    entity_fields = _safe_field_list(main_entity.get("fields") or [])
    router_name = _safe_slug(theme.get("entity_router") or raw_entity_name or "items") or "items"
    table_name = _safe_table_name(raw_entity_name, router_name, project_id)

    return {
        "project_id": project_id,
        "title": title,
        "goal": goal,
        "template_key": template_key,
        "template_name": template_name,
        "router_name": router_name,
        "entity_name": entity_name,
        "entity_fields": entity_fields,
        "table_name": table_name,
    }


def _read_existing_manifest(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def main() -> int:
    project_id = int(os.environ.get("JOB_PROJECT_ID") or os.environ.get("PROJECT_ID") or "0")
    build_target_kind = str(os.environ.get("BUILD_TARGET_KIND") or "").strip().lower()
    job_key = str(os.environ.get("JOB_KEY") or "")
    job_name = str(os.environ.get("JOB_NAME") or "")
    selected_tool = str(os.environ.get("JOB_SELECTED_TOOL") or "")
    adapter_mode = str(os.environ.get("TOOL_ADAPTER_MODE") or "")
    adapter_intent = str(os.environ.get("TOOL_ADAPTER_INTENT") or "")
    build_target_hint = str(os.environ.get("BUILD_TARGET_HINT") or "")

    if project_id <= 0:
        raise SystemExit("JOB_PROJECT_ID is required")
    if build_target_kind not in {"fastapi", "postgres", "alembic"}:
        raise SystemExit(f"unsupported BUILD_TARGET_KIND: {build_target_kind}")

    context = _load_context(project_id)
    project_dir = GENERATED_DIR / f"project_{project_id}" / "codebundle_v2"
    backend_dir = project_dir / "backend"
    migrations_dir = project_dir / "migrations"
    manifest_file = backend_dir / "backend_runtime_manifest.json"

    metadata = {
        "project_id": project_id,
        "job_key": job_key,
        "job_name": job_name,
        "selected_tool": selected_tool,
        "adapter_mode": adapter_mode,
        "adapter_intent": adapter_intent,
        "build_target_kind": build_target_kind,
        "build_target_hint": build_target_hint,
        **context,
    }

    generated_files: List[str] = []
    backend_dir.mkdir(parents=True, exist_ok=True)
    migrations_dir.mkdir(parents=True, exist_ok=True)
    generated_files.append(_write(backend_dir / "__init__.py", ""))

    if build_target_kind == "fastapi":
        router_content = _build_runtime_router_content(
            entity_name=context["entity_name"],
            table_name=context["table_name"],
            router_name=context["router_name"],
            fields=context["entity_fields"],
            project_id=project_id,
            title=context["title"],
            template_name=context["template_name"],
            metadata=metadata,
        )
        schema_content = _prepend_metadata_comment(
            _build_runtime_schema_content(context["entity_name"], context["entity_fields"]),
            metadata,
        )
        service_content = _prepend_metadata_comment(
            _build_runtime_service_content(
                entity_name=context["entity_name"],
                table_name=context["table_name"],
                fields=context["entity_fields"],
                project_id=project_id,
                template_name=context["template_name"],
            ),
            metadata,
        )
        generated_files.append(_write(backend_dir / "router.py", router_content))
        generated_files.append(_write(backend_dir / "schemas.py", schema_content))
        generated_files.append(_write(backend_dir / "service.py", service_content))

    elif build_target_kind == "postgres":
        model_content = _prepend_metadata_comment(
            _build_runtime_model_content(context["entity_name"], context["table_name"], context["entity_fields"]),
            metadata,
        )
        generated_files.append(_write(backend_dir / "models.py", model_content))

    elif build_target_kind == "alembic":
        model_content = _prepend_metadata_comment(
            _build_runtime_model_content(context["entity_name"], context["table_name"], context["entity_fields"]),
            metadata,
        )
        migration_content = _build_runtime_migration_content(
            context["table_name"],
            context["entity_fields"],
            project_id,
            metadata,
        )
        _cleanup_matching_files(migrations_dir, "*.sql")
        _cleanup_matching_files(ROOT_DIR / "sql" / "migrations_v2", f"autofabric_project_{project_id}_*.sql")
        codebundle_migration = migrations_dir / f"001_create_{context['table_name']}.sql"
        repo_migration = ROOT_DIR / "sql" / "migrations_v2" / f"autofabric_project_{project_id}_{context['table_name']}.sql"
        generated_files.append(_write(backend_dir / "models.py", model_content))
        generated_files.append(_write(codebundle_migration, migration_content))
        generated_files.append(_write(repo_migration, migration_content))

    existing_manifest = _read_existing_manifest(manifest_file)
    kind_entries = existing_manifest.get("generated_by_kind") or {}
    kind_entries[build_target_kind] = generated_files
    manifest_payload = {
        "ok": True,
        "project_id": project_id,
        "job_key": job_key,
        "job_name": job_name,
        "selected_tool": selected_tool,
        "adapter_mode": adapter_mode,
        "adapter_intent": adapter_intent,
        "build_target_kind": build_target_kind,
        "build_target_hint": build_target_hint,
        "entity_name": context["entity_name"],
        "entity_fields": context["entity_fields"],
        "router_name": context["router_name"],
        "table_name": context["table_name"],
        "template_key": context["template_key"],
        "template_name": context["template_name"],
        "title": context["title"],
        "goal": context["goal"],
        "generated_by_kind": kind_entries,
    }
    generated_files.append(_write(manifest_file, json.dumps(manifest_payload, ensure_ascii=False, indent=2)))

    print(json.dumps({
        "ok": True,
        "project_id": project_id,
        "build_target_kind": build_target_kind,
        "router_name": context["router_name"],
        "table_name": context["table_name"],
        "entity_name": context["entity_name"],
        "entity_fields": context["entity_fields"],
        "generated_files": generated_files,
        "output_dir": str(project_dir),
    }, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
